#·vim:·set·relativenumber·nonu·shiftwidth=2·tabstop=2·softtabstop=-1·expandtab:
version: '3.7'

services:
  # Frontend
  web:
    image: jitsi/web:latest
    ports:
      - 3035:80
      - 443:443
    volumes:
      - web-config:/config:Z
      - letsencrypt:/etc/letsencrypt:Z
      - transcripts:/usr/share/jitsi-meet/transcripts:Z
    deploy:
      placement:
        constraints:
          - node.labels.tipo == teste
    environment:
      - ENABLE_AUTH=1
      - ENABLE_GUESTS=1
        #- ENABLE_LETSENCRYPT
      - ENABLE_HTTP_REDIRECT
      - ENABLE_TRANSCRIPTIONS
      - DISABLE_HTTPS
      - JICOFO_AUTH_USER
        #- LETSENCRYPT_DOMAIN
        #- LETSENCRYPT_EMAIL
      - PUBLIC_URL
      - XMPP_DOMAIN
      - XMPP_AUTH_DOMAIN
      - XMPP_BOSH_URL_BASE
      - XMPP_GUEST_DOMAIN
      - XMPP_MUC_DOMAIN
      - XMPP_RECORDER_DOMAIN
      - ETHERPAD_URL_BASE
      - ETHERPAD_PUBLIC_URL
      - TZ
      - JIBRI_BREWERY_MUC
      - JIBRI_PENDING_TIMEOUT
      - JIBRI_XMPP_USER
      - JIBRI_XMPP_PASSWORD
      - JIBRI_RECORDER_USER
      - JIBRI_RECORDER_PASSWORD
      - ENABLE_RECORDING
    networks:
      - meet-jitsi
        #        aliases:
          #          - ${XMPP_DOMAIN}

  # XMPP server
  prosody:
    image: jitsi/prosody:latest
    volumes:
      - prosody-config:/config:Z
      - prosody-plugins-custom:/prosody-plugins-custom:Z
    deploy:
      placement:
        constraints:
          - node.labels.tipo == teste
    environment:
      - AUTH_TYPE
      - ENABLE_AUTH
      - ENABLE_GUESTS
      - ENABLE_LOBBY
      - GLOBAL_MODULES
      - GLOBAL_CONFIG
      - LDAP_URL
      - LDAP_BASE
      - LDAP_BINDDN
      - LDAP_BINDPW
      - LDAP_FILTER
      - LDAP_AUTH_METHOD
      - LDAP_VERSION
      - LDAP_USE_TLS
      - LDAP_TLS_CIPHERS
      - LDAP_TLS_CHECK_PEER
      - LDAP_TLS_CACERT_FILE
      - LDAP_TLS_CACERT_DIR
      - LDAP_START_TLS
      - XMPP_DOMAIN
      - XMPP_AUTH_DOMAIN
      - XMPP_GUEST_DOMAIN
      - XMPP_MUC_DOMAIN
      - XMPP_INTERNAL_MUC_DOMAIN
      - XMPP_MODULES
      - XMPP_MUC_MODULES
      - XMPP_INTERNAL_MUC_MODULES
      - XMPP_RECORDER_DOMAIN
      - JICOFO_COMPONENT_SECRET
      - JICOFO_AUTH_USER
      - JICOFO_AUTH_PASSWORD
      - JVB_AUTH_USER
      - JVB_AUTH_PASSWORD
      - JIGASI_XMPP_USER
      - JIGASI_XMPP_PASSWORD
      - JIBRI_XMPP_USER
      - JIBRI_XMPP_PASSWORD
      - JIBRI_RECORDER_USER
      - JIBRI_RECORDER_PASSWORD
      - JWT_APP_ID
      - JWT_APP_SECRET
      - JWT_ACCEPTED_ISSUERS
      - JWT_ACCEPTED_AUDIENCES
      - JWT_ASAP_KEYSERVER
      - JWT_ALLOW_EMPTY
      - JWT_AUTH_TYPE
      - JWT_TOKEN_AUTH_MODULE
      - LOG_LEVEL
      - TZ
    networks:
      - meet-jitsi
        #        aliases:
          #          - ${XMPP_SERVER}

  # Focus component
  jicofo:
    image: jitsi/jicofo:latest
    volumes:
      - jicofo-config:/config:Z
    deploy:
      placement:
        constraints:
          - node.labels.tipo == teste
    environment:
      - AUTH_TYPE
      - ENABLE_AUTH
      - XMPP_DOMAIN
      - XMPP_AUTH_DOMAIN
      - XMPP_INTERNAL_MUC_DOMAIN
      - XMPP_MUC_DOMAIN
      - XMPP_SERVER
      - JICOFO_COMPONENT_SECRET
      - JICOFO_AUTH_USER
      - JICOFO_AUTH_PASSWORD
      - JICOFO_RESERVATION_REST_BASE_URL
      - JVB_BREWERY_MUC
      - JIGASI_BREWERY_MUC
      - JIGASI_SIP_URI
      - JIBRI_BREWERY_MUC
      - JIBRI_PENDING_TIMEOUT
      - TZ
    depends_on:
      - prosody
    networks:
      - meet-jitsi

  # Video bridge
  jvb:
    image: jitsi/jvb:latest
    ports:
      - '10000:10000/udp'
      - '4443:4443'
    volumes:
      - jvb-config:/config:Z
    deploy:
      placement:
        constraints:
          - node.labels.tipo == teste
    environment:
      - DOCKER_HOST_ADDRESS
      - XMPP_AUTH_DOMAIN
      - XMPP_INTERNAL_MUC_DOMAIN
      - XMPP_SERVER
      - JVB_AUTH_USER
      - JVB_AUTH_PASSWORD
      - JVB_BREWERY_MUC
      - JVB_PORT
      - JVB_TCP_HARVESTER_DISABLED
      - JVB_TCP_PORT
      - JVB_STUN_SERVERS
      - JVB_ENABLE_APIS
      - TZ
    depends_on:
      - prosody
    networks:
      - meet-jitsi

#Custom network so all services can communicate using a FQDN
networks:
  meet-jitsi:

volumes:
  web-config:
    driver_opts:
      o: bind
      type: none
      device: /data/jitsi/web/config
  letsencrypt:
    driver_opts:
      o: bind
      type: none
      device: /data/jitsi/web/letsencrypt
  transcripts:
    driver_opts:
      o: bind
      type: none
      device: /data/jitsi/web/transcripts
  prosody-config:
    driver_opts:
      o: bind
      type: none
      device: /data/jitsi/prosody/config
  prosody-plugins-custom:
    driver_opts:
      o: bind
      type: none
      device: /data/jitsi/prosody/prosody-plugins-custom
  jicofo-config: 
    driver_opts:
      o: bind
      type: none
      device: /data/jitsi/jicofo/config
  jvb-config:
    driver_opts:
      o: bind
      type: none
      device: /data/jitsi/jvb/config
